export enum ApiTypes{
    API_SETOR = 'SETOR',
    API_CARGOR = 'CARGO',
    API_TURNO = 'TURNO',
    API_FUNCIONARIO = 'FUNCIONARIO',
    API_PROFISSIONAL = 'PROFISSIONAL',
    API_ABSENTEISMO = 'ABSENTEISMO',
    API_AFASTAMENTO = 'AFASTAMENTO',
}